//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnlimitedInf.LectureConvert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnlimitedInf.LectureConvert.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} does not exist. Creating..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LECTURECONVERT: {0}.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LECTURECONVERT: Invalid line in INPUTFILE: {0}.
        /// </summary>
        internal static string ErrorText_InvalidInputLine {
            get {
                return ResourceManager.GetString("ErrorText_InvalidInputLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LECTURECONVERT: Must have one INPUTFILE..
        /// </summary>
        internal static string ErrorText_MustHaveInputFile {
            get {
                return ResourceManager.GetString("ErrorText_MustHaveInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i {0} -vn -q:a 0 {1}.
        /// </summary>
        internal static string FFMpegCommand {
            get {
                return ResourceManager.GetString("FFMpegCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lectures remaining. . ..
        /// </summary>
        internal static string FFMpegOverallStatus {
            get {
                return ResourceManager.GetString("FFMpegOverallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core {0} / Lec {1}: {2}.
        /// </summary>
        internal static string FFMpegStatus {
            get {
                return ResourceManager.GetString("FFMpegStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC: {0}.
        /// </summary>
        internal static string LogText {
            get {
                return ResourceManager.GetString("LogText", resourceCulture);
            }
        }
    }
}
